id: P000093
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཆོས་བཤད་གཞན་ཕན་ཉི་མ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  layers:
  - book_title
  - author
  - quotation
  id: SHE-SHAP-11
web_metadata:
  title:
    en: The Beneficial Sun:The Public Teaching of Shabkar
    bo: ཆོས་བཤད་གཞན་ཕན་ཉི་མ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 11
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༡༡
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-11
  category:
    en: Dharma Teaching
    bo: ཆོས་བསླབ་བྱ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-11.epub
  description:
    en: ''
    bo: ''
